version: '3'
services:
  app:
    build: .
    container_name: prodex_application
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: prodex_mongo_application
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:latest 
    container_name: prodex_redis
    ports:
      - "6379:6379" 
    restart: always

volumes:
  mongo_data:
